### ISSUE TITLE
Rewrite web page with react

### ISSUE THREAD

**Issue by cecilehabran** [cecilehabran/responsive-story#7]
@DavidBruant 
See gist https://gist.github.com/cecilehabran/493e2532da673f4f7345a038610f72cf

Is that a good idea to setState on interval? Or _i_ shouldn't be a state of the component at all ?

((It just for actually try it, I'm not sure it makes sense to load React for such a small thingy)

**Comment by DavidBruant** [comment]
`class Cecile extends React.Component` <3

> Is that a good idea to setState on interval? Or i shouldn't be a state of the component at all ?

There are 2 ways of doing it:
- either the component has `i` as props (maybe it should be the `{job, color, misc}` but whatever)
- or the component has `i` as state

You chose state, it works really well.

The `setState` in the interval works really well. `componentDidMount` is the right place to start it!

Suggestions:
- Maybe you could `clearInterval` on `componentWillUnmount`
- the `randomChange` is not random ;-) Also, the code feels a bit complicated `this.setState({i: (this.state.i+1)%3})` should do the trick. [% is the remainder operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Remainder_())
- I think that the color/job/misc will always be synced (always same triplets on screen). Is that intended?

**Comment by cecilehabran** [comment]
Crap you're fast.
`class Cecile` on purpose, glad you like it. I'm basically the component of my web page, right ?!

Got it for the sync of color/job/misc, changing that.

**Comment by DavidBruant** [comment]
> Crap you're fast.

Really a coincidence, i was checking my email for something else :-p

> Maybe you could clearInterval on componentWillUnmount
> Hum, that's already the case isn't it?

... yeah... literally no clue why i missed it, sorry for the noise
